version: '2'

services:

  ecobici-counts:
    image: dockerized/slave
    container_name: ecobici-counts
    hostname: ecobici-counts
    environment:
      - INPUT=/datasets/ecobici/*
      - OUTPUT=/datasets/ecobici-count-per-station/
    volumes:
      - ../jobs/ecobici/count-per-station:/jobs
    command: /jobs/run-in-hadoop.sh


  flights-mapper-join:
    image: dockerized/slave
    container_name: flighs-mapper-join
    hostname: flighs-mapper-join
    working_dir: /jobs
    environment:
      - INPUT=/datasets/flights/flights.csv
      - OUTPUT=/datasets/flights-mapper-join/
    volumes:
      - ../jobs/flights/mapper-join:/jobs
    command: /jobs/run-in-hadoop.sh


  datasets:
    image: dockerized/slave
    container_name: datasets
    hostname: datasets
    working_dir: /datasets
    volumes:
      - ../datasets:/datasets
    command: /bin/bash
    tty: true
